### ISSUE TITLE
how it ll work from port to interface

### ISSUE THREAD

**Issue by sandeepbs39** [mscdex/cap#28] opened 2015-05-29 08:35 UTC
Capture and decode all outgoing TCP data packets destined for port 80 on the interface for 192.168.0.10: but i want to capture and decode all TCP packets from Port 80 to the interface 192.168.0.10 i.e it should capture and decode the packets in both ways...

**Comment by mscdex** [comment] 2015-05-29 12:11
Duplicate of #27.

**Closed by mscdex** 2015-05-29 12:11 UTC
